/**
 * 6岁儿童视频推荐专区 - 精选视频数据库
 *
 * 策展标准：
 * - 适合6岁儿童（学龄前/幼小衔接）
 * - 无暴力、无恐怖、无成人暗示、无危险模仿内容
 * - 节奏适中，不过度刺激
 * - 有教育价值：学习/认知/情绪管理/社交能力
 * - 来源可靠：YouTube官方频道（PBS Kids/Sesame Street/National Geographic Kids等）
 * - 时长：3-12分钟为主，最长不超过20分钟
 * - 语言：英文为主
 *
 * 最后更新：2026-01
 */

const videoDatabase = {
  // 元数据
  meta: {
    version: "1.0.0",
    lastUpdated: "2026-01-20",
    targetAge: 6,
    ageRange: "5-7岁",
    totalVideos: 30,
    language: "英文为主"
  },

  // 分类定义
  categories: [
    {
      id: "math",
      name: "数学启蒙",
      nameEn: "Math Foundation",
      icon: "🔢",
      description: "加减法、数感、规律认知",
      color: "#FF6B6B"
    },
    {
      id: "english",
      name: "英语启蒙",
      nameEn: "English Learning",
      icon: "🔤",
      description: "自然拼读、词汇、简单对话",
      color: "#4ECDC4"
    },
    {
      id: "science",
      name: "科普探索",
      nameEn: "Science Discovery",
      icon: "🔬",
      description: "动物、人体、太空、自然现象",
      color: "#45B7D1"
    },
    {
      id: "emotion",
      name: "情绪与品格",
      nameEn: "Emotions & Character",
      icon: "💝",
      description: "情绪管理、礼貌、合作、勇气",
      color: "#96CEB4"
    },
    {
      id: "brain",
      name: "专注力与脑力",
      nameEn: "Focus & Brain Training",
      icon: "🧠",
      description: "逻辑、观察、记忆、思维训练",
      color: "#DDA0DD"
    },
    {
      id: "music",
      name: "音乐与运动",
      nameEn: "Music & Movement",
      icon: "🎵",
      description: "儿歌、律动、亲子运动",
      color: "#FFD93D"
    }
  ],

  // 视频数据 - 2026年1月更新，已验证可用
  videos: [
    // ==================== 数学启蒙 (5个) ====================
    {
      id: "math-001",
      category: "math",
      title: "Learning Colors and Numbers Song | Colorful Eggs",
      titleZh: "学习颜色和数字：彩色鸡蛋",
      youtubeId: "cX2Bg7ZVCe4",
      channel: "ZuZoo Nursery Rhymes",
      channelType: "educational",
      duration: "10:00",
      durationMinutes: 10,
      thumbnail: "🔢",
      ageMin: 3,
      ageMax: 7,
      skills: ["颜色认知", "数数", "视觉学习"],
      description: "通过农场彩色鸡蛋学习颜色和数字，培养基础数感。",
      whyRecommend: "全球超高播放量的儿童教育视频，色彩鲜艳，节奏适中，非常适合幼儿。",
      safetyNotes: "内容纯净，无任何不适内容，节奏平缓。",
      parentTips: "可以和孩子一起用彩色积木或玩具蛋练习颜色和数字。"
    },
    {
      id: "math-002",
      category: "math",
      title: "Johny Johny Yes Papa - Learning Nursery Rhyme",
      titleZh: "约翰尼约翰尼：学习儿歌",
      youtubeId: "F4tHL8reNCs",
      channel: "LooLoo Kids",
      channelType: "official",
      duration: "4:00",
      durationMinutes: 4,
      thumbnail: "➕",
      ageMin: 3,
      ageMax: 6,
      skills: ["语言学习", "数字认知", "韵律感"],
      description: "经典儿歌帮助孩子学习简单的英语词汇和对话。",
      whyRecommend: "全球69亿+播放量，简单重复的歌词帮助孩子快速学习基础英语。",
      safetyNotes: "纯教育内容，画面简洁明快。",
      parentTips: "鼓励孩子跟唱，用动作配合歌词。"
    },
    {
      id: "math-003",
      category: "math",
      title: "Baa Baa Black Sheep | Counting Wool",
      titleZh: "黑绵羊咩咩：数羊毛",
      youtubeId: "MR5XSOdjKMA",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "➖",
      ageMin: 3,
      ageMax: 6,
      skills: ["数数", "分配概念", "韵律"],
      description: "经典童谣学习数数和分配概念。",
      whyRecommend: "Cocomelon官方出品，画风可爱，通过经典童谣教授数学概念。",
      safetyNotes: "内容积极向上，无不适画面。",
      parentTips: "可用零食或玩具演示分配过程。"
    },
    {
      id: "math-004",
      category: "math",
      title: "Learn About the 7 Continents",
      titleZh: "认识七大洲",
      youtubeId: "K-74JQweOQE",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "20:00",
      durationMinutes: 20,
      thumbnail: "🔟",
      ageMin: 5,
      ageMax: 9,
      skills: ["地理知识", "数字概念", "世界认知"],
      description: "学习世界七大洲的名称和特点，建立地理数字概念。",
      whyRecommend: "国家地理官方出品，内容权威准确，用7这个数字串联地理知识。",
      safetyNotes: "画风友好，节奏适中。",
      parentTips: "可以配合地球仪或地图一起学习。"
    },
    {
      id: "math-005",
      category: "math",
      title: "Animal Alphabet | Learn Letters A-Z",
      titleZh: "动物字母表：学习A-Z",
      youtubeId: "tlhjcLRT07w",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "5:00",
      durationMinutes: 5,
      thumbnail: "🔵🔴",
      ageMin: 4,
      ageMax: 7,
      skills: ["字母学习", "计数", "动物认知"],
      description: "通过26个字母和对应的动物学习字母表和数字序列。",
      whyRecommend: "国家地理官方出品，用动物图片激发学习兴趣，26个字母建立数字序列感。",
      safetyNotes: "纯教育内容，讲解温和清晰。",
      parentTips: "可以用动物卡片配合学习字母和数字顺序。"
    },

    // ==================== 英语启蒙 (5个) ====================
    {
      id: "english-001",
      category: "english",
      title: "Wheels on the Bus | CoComelon Nursery Rhymes",
      titleZh: "公交车之歌：经典童谣",
      youtubeId: "e_04ZrNroTo",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🍎",
      ageMin: 2,
      ageMax: 6,
      skills: ["英语词汇", "动作模仿", "节奏感"],
      description: "全球最受欢迎的儿童英语歌曲之一，学习交通和动作词汇。",
      whyRecommend: "Cocomelon王牌视频，61亿+播放量，经典童谣帮助孩子学习英语词汇和动作。",
      safetyNotes: "内容纯净，全程正面教育内容。",
      parentTips: "坐公交或开车时可以和孩子一起唱，配合手势动作。"
    },
    {
      id: "english-002",
      category: "english",
      title: "Bath Song | CoComelon Nursery Rhymes",
      titleZh: "洗澡歌：好习惯养成",
      youtubeId: "WRVsOCh907o",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🌈",
      ageMin: 2,
      ageMax: 6,
      skills: ["身体部位词汇", "卫生习惯", "日常英语"],
      description: "通过洗澡歌学习身体部位的英语表达和良好卫生习惯。",
      whyRecommend: "Cocomelon超高人气视频，68亿+播放量，教育价值高，帮助孩子养成好习惯。",
      safetyNotes: "画面温馨，家庭场景为主，非常安全。",
      parentTips: "洗澡时可以和孩子一起唱，指认身体各部位的英文名称。"
    },
    {
      id: "english-003",
      category: "english",
      title: "If You're Happy and You Know It | HooplaKidz",
      titleZh: "如果感到幸福你就拍拍手",
      youtubeId: "ufyrxaQRZrg",
      channel: "HooplaKidz",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🌅",
      ageMin: 3,
      ageMax: 7,
      skills: ["情绪词汇", "动作指令", "互动学习"],
      description: "经典互动儿歌，学习情绪表达和动作指令英语。",
      whyRecommend: "全球经典儿歌，简单好学，通过身体动作加深英语学习记忆。",
      safetyNotes: "内容积极正面，鼓励表达快乐情绪。",
      parentTips: "可以在家一起做动作，创造新歌词版本。"
    },
    {
      id: "english-004",
      category: "english",
      title: "Amazing Animals | National Geographic Kids",
      titleZh: "神奇动物：英语科普",
      youtubeId: "eUunYTYia3I",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "60:00",
      durationMinutes: 60,
      thumbnail: "🌤️",
      ageMin: 5,
      ageMax: 9,
      skills: ["动物词汇", "科普英语", "听力理解"],
      description: "1小时精选动物科普合集，学习丰富的动物相关英语词汇。",
      whyRecommend: "国家地理官方出品，画面精美，内容权威，边看边学习动物英语。",
      safetyNotes: "内容科普性强，画面友好，适合儿童观看。",
      parentTips: "可以分段观看，每次看几种动物，讨论学到的新单词。"
    },
    {
      id: "english-005",
      category: "english",
      title: "First Big Book of Dinosaurs | Nat Geo Kids",
      titleZh: "恐龙大百科：英语版",
      youtubeId: "RQUBw24mbvc",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "15:00",
      durationMinutes: 15,
      thumbnail: "😊",
      ageMin: 4,
      ageMax: 8,
      skills: ["恐龙词汇", "科普英语", "听力理解"],
      description: "通过恐龙主题学习英语词汇和科普知识。",
      whyRecommend: "孩子们最爱的恐龙主题，国家地理官方出品，激发学习英语的兴趣。",
      safetyNotes: "科普内容为主，画面适合儿童，不含恐怖场景。",
      parentTips: "可以配合恐龙玩具或图书，讨论视频中的恐龙名称。"
    },

    // ==================== 科普探索 (5个) ====================
    {
      id: "science-001",
      category: "science",
      title: "Evolution of Dogs | Weird But True",
      titleZh: "狗的进化：奇妙事实",
      youtubeId: "sSTzh0ba3vM",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "22:00",
      durationMinutes: 22,
      thumbnail: "🦕",
      ageMin: 5,
      ageMax: 9,
      skills: ["进化知识", "动物科学", "科学思维"],
      description: "了解狗是如何从单一祖先进化成300多种品种的。",
      whyRecommend: "国家地理官方内容，真人主持有趣，探索孩子最爱的宠物主题。",
      safetyNotes: "内容科学准确，画面友好，适合儿童观看。",
      parentTips: "如果家里有狗狗，可以讨论它是什么品种，有什么特点。"
    },
    {
      id: "science-002",
      category: "science",
      title: "Masha and the Bear - Recipe for Disaster",
      titleZh: "玛莎和熊：灾难配方",
      youtubeId: "qBp1rCz_yQU",
      channel: "Masha and the Bear",
      channelType: "official",
      duration: "7:00",
      durationMinutes: 7,
      thumbnail: "🪐",
      ageMin: 3,
      ageMax: 8,
      skills: ["因果关系", "问题解决", "生活常识"],
      description: "通过有趣的故事学习因果关系和生活常识。",
      whyRecommend: "全球超受欢迎的动画系列，幽默有趣，蕴含生活智慧和科学道理。",
      safetyNotes: "卡通动画，内容温馨有趣，适合儿童。",
      parentTips: "观看后可以讨论玛莎做了什么，为什么会有那样的结果。"
    },
    {
      id: "science-003",
      category: "science",
      title: "Baby Shark Dance | Pinkfong",
      titleZh: "鲨鱼宝宝：海洋知识",
      youtubeId: "XqZsoesa55w",
      channel: "Pinkfong",
      channelType: "official",
      duration: "2:17",
      durationMinutes: 2.5,
      thumbnail: "❤️",
      ageMin: 2,
      ageMax: 7,
      skills: ["海洋动物", "家庭关系", "节奏感"],
      description: "全球最受欢迎的儿童歌曲，学习鲨鱼家庭和海洋知识。",
      whyRecommend: "全球164亿+播放量的顶级儿童视频，寓教于乐，培养海洋兴趣。",
      safetyNotes: "卡通风格，不含任何恐怖元素，非常安全。",
      parentTips: "可以配合手势动作，全家一起唱跳。"
    },
    {
      id: "science-004",
      category: "science",
      title: "Amazing Animals 1 Hour Compilation",
      titleZh: "神奇动物1小时合集",
      youtubeId: "eUunYTYia3I",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "60:00",
      durationMinutes: 60,
      thumbnail: "🍂",
      ageMin: 4,
      ageMax: 9,
      skills: ["动物知识", "生态意识", "科学思维"],
      description: "1小时精选动物科普，包括树袋鼠、蓝鲸、海马、北极熊等。",
      whyRecommend: "国家地理官方精选合集，内容丰富权威，画面震撼，满足孩子的好奇心。",
      safetyNotes: "纯科普内容，画面友好，适合儿童长时间观看。",
      parentTips: "可以分段观看，每次讨论几种动物的特点。"
    },
    {
      id: "science-005",
      category: "science",
      title: "Learn About the 7 Continents | Destination World",
      titleZh: "认识七大洲：目的地世界",
      youtubeId: "K-74JQweOQE",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "20:00",
      durationMinutes: 20,
      thumbnail: "🐙",
      ageMin: 5,
      ageMax: 9,
      skills: ["地理知识", "世界认知", "文化意识"],
      description: "探索世界七大洲的自然风光和人文特色。",
      whyRecommend: "国家地理官方出品，带孩子环游世界，开阔视野，激发探索欲。",
      safetyNotes: "画面优美，内容积极，对儿童友好。",
      parentTips: "可以配合地图或地球仪，找找视频中提到的地方。"
    },

    // ==================== 情绪与品格 (5个) ====================
    {
      id: "emotion-001",
      category: "emotion",
      title: "Try a Little Kindness | Sesame Street with Tori Kelly",
      titleZh: "善良一点点：芝麻街",
      youtubeId: "enaRNnEzwi4",
      channel: "Sesame Street",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🐯",
      ageMin: 3,
      ageMax: 7,
      skills: ["善良品格", "同理心", "积极态度"],
      description: "和Tori Kelly及芝麻街伙伴们一起学习善良的重要性。",
      whyRecommend: "芝麻街经典品格教育，配合流行歌手演唱，旋律优美，传递善良的价值观。",
      safetyNotes: "内容温暖治愈，正面引导品格发展。",
      parentTips: "和孩子讨论日常生活中可以如何展现善良。"
    },
    {
      id: "emotion-002",
      category: "emotion",
      title: "Masha and the Bear - Learning Life Lessons",
      titleZh: "玛莎和熊：生活小智慧",
      youtubeId: "qBp1rCz_yQU",
      channel: "Masha and the Bear",
      channelType: "official",
      duration: "7:00",
      durationMinutes: 7,
      thumbnail: "❤️",
      ageMin: 3,
      ageMax: 8,
      skills: ["因果思维", "责任感", "解决问题"],
      description: "通过玛莎的冒险故事学习生活中的道理和责任感。",
      whyRecommend: "全球爆火动画，53亿+播放量，有趣的故事蕴含深刻的人生道理。",
      safetyNotes: "内容纯净正面，传递积极价值观。",
      parentTips: "观看后讨论玛莎的行为产生了什么后果，我们可以怎么做得更好。"
    },
    {
      id: "emotion-003",
      category: "emotion",
      title: "If You're Happy and You Know It | Express Emotions",
      titleZh: "如果感到幸福：情绪表达",
      youtubeId: "ufyrxaQRZrg",
      channel: "HooplaKidz",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🤝",
      ageMin: 2,
      ageMax: 6,
      skills: ["情绪表达", "身体语言", "积极心态"],
      description: "通过经典儿歌学习用身体动作表达快乐情绪。",
      whyRecommend: "全球经典儿歌，帮助孩子认识和表达积极情绪，培养乐观心态。",
      safetyNotes: "正面情绪引导，内容健康向上。",
      parentTips: "可以创造新歌词，表达其他情绪：如果感到生气你就跺跺脚。"
    },
    {
      id: "emotion-004",
      category: "emotion",
      title: "Johny Johny Yes Papa - Honesty Song",
      titleZh: "约翰尼：诚实的重要性",
      youtubeId: "F4tHL8reNCs",
      channel: "LooLoo Kids",
      channelType: "official",
      duration: "4:00",
      durationMinutes: 4,
      thumbnail: "🔄",
      ageMin: 2,
      ageMax: 6,
      skills: ["诚实品格", "亲子关系", "规则意识"],
      description: "通过经典儿歌学习诚实的重要性。",
      whyRecommend: "69亿+播放量的经典儿歌，通过简单故事教导诚实的价值。",
      safetyNotes: "内容积极正面，场景贴近儿童生活。",
      parentTips: "和孩子讨论为什么诚实很重要，以及如何做一个诚实的人。"
    },
    {
      id: "emotion-005",
      category: "emotion",
      title: "Bath Song - Building Good Habits",
      titleZh: "洗澡歌：养成好习惯",
      youtubeId: "WRVsOCh907o",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "💪",
      ageMin: 2,
      ageMax: 6,
      skills: ["习惯养成", "自理能力", "卫生意识"],
      description: "通过有趣的歌曲培养孩子良好的卫生习惯和自理能力。",
      whyRecommend: "Cocomelon王牌视频，68亿+播放量，帮助孩子爱上洗澡，养成好习惯。",
      safetyNotes: "内容温馨积极，画面友好。",
      parentTips: "洗澡时播放这首歌，让洗澡变成有趣的活动。"
    },

    // ==================== 专注力与脑力 (5个) ====================
    {
      id: "brain-001",
      category: "brain",
      title: "Learning Colors - Colorful Eggs Farm | Focus Training",
      titleZh: "学习颜色：专注力训练",
      youtubeId: "cX2Bg7ZVCe4",
      channel: "Miroshka TV",
      channelType: "educational",
      duration: "10:00",
      durationMinutes: 10,
      thumbnail: "👀",
      ageMin: 3,
      ageMax: 7,
      skills: ["观察力", "颜色辨识", "专注力"],
      description: "通过观察彩色鸡蛋训练专注力和观察能力。",
      whyRecommend: "全球超高播放量视频，色彩鲜艳但节奏平缓，适合训练孩子的专注力。",
      safetyNotes: "纯益智内容，无任何不适元素。",
      parentTips: "可以暂停视频让孩子预测下一个颜色。"
    },
    {
      id: "brain-002",
      category: "brain",
      title: "Animal Alphabet | Memory & Recognition",
      titleZh: "动物字母表：记忆训练",
      youtubeId: "tlhjcLRT07w",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "5:00",
      durationMinutes: 5,
      thumbnail: "🧩",
      ageMin: 4,
      ageMax: 7,
      skills: ["短期记忆", "字母认知", "动物识别"],
      description: "通过A-Z动物字母表训练记忆力和认知能力。",
      whyRecommend: "国家地理官方出品，26个字母配26种动物，帮助孩子建立记忆联系。",
      safetyNotes: "卡通风格，内容纯净，适合独立观看。",
      parentTips: "可以让孩子回忆：A是什么动物？B是什么动物？"
    },
    {
      id: "brain-003",
      category: "brain",
      title: "Baby Shark | Rhythm & Pattern Recognition",
      titleZh: "鲨鱼宝宝：节奏与规律",
      youtubeId: "XqZsoesa55w",
      channel: "Pinkfong",
      channelType: "official",
      duration: "2:17",
      durationMinutes: 2.5,
      thumbnail: "❓",
      ageMin: 2,
      ageMax: 6,
      skills: ["节奏感", "规律识别", "动作协调"],
      description: "通过歌曲学习重复的节奏规律，训练协调能力。",
      whyRecommend: "全球最受欢迎儿童歌曲，重复的歌词和动作帮助孩子识别规律模式。",
      safetyNotes: "纯益智内容，画面友好。",
      parentTips: "可以让孩子预测下一段是谁（爸爸、妈妈、爷爷、奶奶）。"
    },
    {
      id: "brain-004",
      category: "brain",
      title: "Wheels on the Bus | Sequence & Memory",
      titleZh: "公交车之歌：顺序与记忆",
      youtubeId: "e_04ZrNroTo",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🔮",
      ageMin: 2,
      ageMax: 6,
      skills: ["顺序记忆", "动作模仿", "预测能力"],
      description: "通过重复的歌词结构训练顺序记忆和预测能力。",
      whyRecommend: "经典儿歌，重复但有变化的结构帮助孩子学习顺序和预测。",
      safetyNotes: "教育内容，画面清晰简洁。",
      parentTips: "可以让孩子预测下一段是什么：轮子、雨刷、喇叭..."
    },
    {
      id: "brain-005",
      category: "brain",
      title: "Amazing Animals | Observation Skills",
      titleZh: "神奇动物：观察力训练",
      youtubeId: "eUunYTYia3I",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "60:00",
      durationMinutes: 60,
      thumbnail: "🌀",
      ageMin: 4,
      ageMax: 9,
      skills: ["观察力", "信息处理", "专注力"],
      description: "通过观察各种动物的特征训练观察力和信息处理能力。",
      whyRecommend: "国家地理官方合集，丰富的动物细节帮助训练孩子的观察能力。",
      safetyNotes: "科普内容，场景友好无压力。",
      parentTips: "可以分段观看，让孩子描述看到了什么动物，有什么特点。"
    },

    // ==================== 音乐与运动 (5个) ====================
    {
      id: "music-001",
      category: "music",
      title: "Baby Shark Dance | Pinkfong",
      titleZh: "鲨鱼宝宝舞：全身律动",
      youtubeId: "XqZsoesa55w",
      channel: "Pinkfong",
      channelType: "official",
      duration: "2:17",
      durationMinutes: 2.5,
      thumbnail: "🙆",
      ageMin: 2,
      ageMax: 7,
      skills: ["身体协调", "节奏感", "动作模仿"],
      description: "全球最火儿童歌曲，配合手势舞蹈活动全身。",
      whyRecommend: "全球164亿+播放量的超级儿歌，简单重复的动作帮助孩子活动身体。",
      safetyNotes: "动作简单安全，节奏适中。",
      parentTips: "全家一起做手势动作，增加亲子互动乐趣。"
    },
    {
      id: "music-002",
      category: "music",
      title: "Wheels on the Bus | Action Song",
      titleZh: "公交车之歌：动作歌曲",
      youtubeId: "e_04ZrNroTo",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🕺",
      ageMin: 2,
      ageMax: 6,
      skills: ["动作模仿", "节奏感", "想象力"],
      description: "经典儿歌配合丰富的动作，让孩子动起来。",
      whyRecommend: "Cocomelon王牌视频，每段歌词配不同动作，帮助孩子释放能量。",
      safetyNotes: "室内可安全进行，不需要额外器材。",
      parentTips: "可以模仿视频中的动作：转圈圈、刷雨刷、按喇叭等。"
    },
    {
      id: "music-003",
      category: "music",
      title: "If You're Happy and You Know It | Movement Song",
      titleZh: "如果感到幸福：动起来",
      youtubeId: "ufyrxaQRZrg",
      channel: "HooplaKidz",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🐸",
      ageMin: 2,
      ageMax: 7,
      skills: ["动作协调", "听觉反应", "情绪表达"],
      description: "经典互动儿歌，听指令做动作，活动全身。",
      whyRecommend: "全球经典儿歌，拍手、跺脚、喊万岁，让孩子开心运动。",
      safetyNotes: "动作设计安全，适合室内进行。",
      parentTips: "可以加快节奏，增加挑战性和趣味性。"
    },
    {
      id: "music-004",
      category: "music",
      title: "Bath Song | Sing Along Dance",
      titleZh: "洗澡歌：跟唱跟跳",
      youtubeId: "WRVsOCh907o",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "👏",
      ageMin: 2,
      ageMax: 6,
      skills: ["身体部位认知", "动作模仿", "节奏感"],
      description: "跟着歌曲做洗澡动作，学习身体部位。",
      whyRecommend: "Cocomelon超人气视频，边唱边指认身体部位，寓教于乐。",
      safetyNotes: "动作简单安全，适合任何场合。",
      parentTips: "洗澡时可以播放，让孩子跟着做动作。"
    },
    {
      id: "music-005",
      category: "music",
      title: "Baa Baa Black Sheep | Nursery Rhyme Dance",
      titleZh: "黑绵羊咩咩：童谣舞蹈",
      youtubeId: "MR5XSOdjKMA",
      channel: "Cocomelon",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "🧘",
      ageMin: 2,
      ageMax: 6,
      skills: ["节奏感", "动作协调", "歌唱能力"],
      description: "经典童谣配合可爱动画，让孩子跟唱跟跳。",
      whyRecommend: "Cocomelon经典童谣，简单好学，帮助孩子建立音乐节奏感。",
      safetyNotes: "内容温馨友好，适合睡前或活动时间。",
      parentTips: "可以和孩子一起唱，鼓励孩子大声唱出来。"
    }
  ]
};

// 导出供其他模块使用
if (typeof module !== 'undefined' && module.exports) {
  module.exports = videoDatabase;
}
