/**
 * 6岁儿童视频推荐专区 - 精选视频数据库
 *
 * 策展标准：
 * - 适合6岁儿童（学龄前/幼小衔接）
 * - 无暴力、无恐怖、无成人暗示、无危险模仿内容
 * - 节奏适中，不过度刺激
 * - 有教育价值：学习/认知/情绪管理/社交能力
 * - 来源可靠：YouTube官方频道（PBS Kids/Sesame Street/National Geographic Kids等）
 * - 时长：3-12分钟为主，最长不超过20分钟
 * - 语言：英文为主
 *
 * 最后更新：2026-01
 */

const videoDatabase = {
  // 元数据
  meta: {
    version: "1.0.0",
    lastUpdated: "2026-01-20",
    targetAge: 6,
    ageRange: "5-7岁",
    totalVideos: 30,
    language: "英文为主"
  },

  // 分类定义
  categories: [
    {
      id: "math",
      name: "数学启蒙",
      nameEn: "Math Foundation",
      icon: "🔢",
      description: "加减法、数感、规律认知",
      color: "#FF6B6B"
    },
    {
      id: "english",
      name: "英语启蒙",
      nameEn: "English Learning",
      icon: "🔤",
      description: "自然拼读、词汇、简单对话",
      color: "#4ECDC4"
    },
    {
      id: "science",
      name: "科普探索",
      nameEn: "Science Discovery",
      icon: "🔬",
      description: "动物、人体、太空、自然现象",
      color: "#45B7D1"
    },
    {
      id: "emotion",
      name: "情绪与品格",
      nameEn: "Emotions & Character",
      icon: "💝",
      description: "情绪管理、礼貌、合作、勇气",
      color: "#96CEB4"
    },
    {
      id: "brain",
      name: "专注力与脑力",
      nameEn: "Focus & Brain Training",
      icon: "🧠",
      description: "逻辑、观察、记忆、思维训练",
      color: "#DDA0DD"
    },
    {
      id: "music",
      name: "音乐与运动",
      nameEn: "Music & Movement",
      icon: "🎵",
      description: "儿歌、律动、亲子运动",
      color: "#FFD93D"
    }
  ],

  // 视频数据
  videos: [
    // ==================== 数学启蒙 (5个) ====================
    {
      id: "math-001",
      category: "math",
      title: "Numberblocks - The Whole of Me",
      titleZh: "数字积木：完整的我",
      youtubeId: "Pj8MHJKBwqQ",
      channel: "Numberblocks",
      channelType: "official",
      duration: "5:00",
      durationMinutes: 5,
      thumbnail: "🔢",
      ageMin: 4,
      ageMax: 7,
      skills: ["数感", "加法概念", "数字组合"],
      description: "通过可爱的数字角色学习数字如何组合，培养基础数感。",
      whyRecommend: "BBC官方出品，画风可爱，用视觉化方式展示数字组合，非常适合6岁孩子建立数感基础。",
      safetyNotes: "内容纯净，无任何不适内容，节奏平缓。",
      parentTips: "可以和孩子一起用积木模仿视频中的数字组合。"
    },
    {
      id: "math-002",
      category: "math",
      title: "Addition Song for Kids | Adding Up to 10",
      titleZh: "加法歌：10以内加法",
      youtubeId: "WT_wvvEvkw0",
      channel: "Jack Hartmann Kids Music Channel",
      channelType: "educational",
      duration: "3:30",
      durationMinutes: 3.5,
      thumbnail: "➕",
      ageMin: 5,
      ageMax: 7,
      skills: ["10以内加法", "数学歌曲", "心算"],
      description: "通过朗朗上口的歌曲学习10以内加法，边唱边算。",
      whyRecommend: "音乐节奏适中，歌词简单重复，帮助孩子在愉快氛围中记忆加法。",
      safetyNotes: "纯教育内容，画面简洁明快。",
      parentTips: "鼓励孩子跟唱，用手指比划数字。"
    },
    {
      id: "math-003",
      category: "math",
      title: "Subtraction Song for Kids",
      titleZh: "减法歌：学习减法",
      youtubeId: "QkPa9V2wtZs",
      channel: "Jack Hartmann Kids Music Channel",
      channelType: "educational",
      duration: "4:00",
      durationMinutes: 4,
      thumbnail: "➖",
      ageMin: 5,
      ageMax: 7,
      skills: ["减法概念", "数学歌曲", "倒数"],
      description: "用音乐和动作学习减法概念，理解'减少'的含义。",
      whyRecommend: "与加法歌配套，帮助孩子理解加减法的对应关系，歌曲朗朗上口。",
      safetyNotes: "内容积极向上，无不适画面。",
      parentTips: "可用零食或玩具实物演示减法过程。"
    },
    {
      id: "math-004",
      category: "math",
      title: "Counting by Tens | Skip Counting Song",
      titleZh: "10个10个数：跳数歌",
      youtubeId: "W8CEOlAOGas",
      channel: "Scratch Garden",
      channelType: "educational",
      duration: "3:15",
      durationMinutes: 3.25,
      thumbnail: "🔟",
      ageMin: 5,
      ageMax: 8,
      skills: ["跳数", "数列规律", "10的倍数"],
      description: "学习10、20、30...100的跳数规律，为大数概念打基础。",
      whyRecommend: "幼小衔接关键技能，用歌曲帮助记忆，为未来学习乘法打基础。",
      safetyNotes: "画风卡通友好，节奏欢快但不急促。",
      parentTips: "可以在日常生活中练习数10元钱币。"
    },
    {
      id: "math-005",
      category: "math",
      title: "Patterns for Kids | AB, AAB, ABB Patterns",
      titleZh: "规律认知：找规律",
      youtubeId: "CXXU7K1dWKQ",
      channel: "Homeschool Pop",
      channelType: "educational",
      duration: "6:00",
      durationMinutes: 6,
      thumbnail: "🔵🔴",
      ageMin: 5,
      ageMax: 7,
      skills: ["模式识别", "逻辑思维", "规律延续"],
      description: "学习识别和延续不同类型的规律模式，培养逻辑思维。",
      whyRecommend: "规律认知是数学思维的基础，视频讲解清晰，例子丰富。",
      safetyNotes: "纯教育内容，讲解温和清晰。",
      parentTips: "生活中可用积木、水果排列规律让孩子练习。"
    },

    // ==================== 英语启蒙 (5个) ====================
    {
      id: "english-001",
      category: "english",
      title: "Phonics Song with TWO Words - A For Apple",
      titleZh: "自然拼读歌：A-Z字母发音",
      youtubeId: "BELlZKpi1Zs",
      channel: "ChuChu TV",
      channelType: "official",
      duration: "4:30",
      durationMinutes: 4.5,
      thumbnail: "🍎",
      ageMin: 4,
      ageMax: 7,
      skills: ["自然拼读", "字母发音", "单词联想"],
      description: "每个字母配两个单词，学习字母在单词中的发音。",
      whyRecommend: "自然拼读是英语阅读基础，歌曲朗朗上口，画面精美，重复强化记忆。",
      safetyNotes: "内容纯净，全程正面教育内容。",
      parentTips: "每次可以专注学习3-5个字母，不必一次学完。"
    },
    {
      id: "english-002",
      category: "english",
      title: "Learn Colors, Numbers and ABCs | Kids Songs",
      titleZh: "颜色、数字和字母学习歌",
      youtubeId: "LhKglCeZNdI",
      channel: "Cocomelon",
      channelType: "official",
      duration: "8:00",
      durationMinutes: 8,
      thumbnail: "🌈",
      ageMin: 3,
      ageMax: 6,
      skills: ["颜色词汇", "数字英语", "字母复习"],
      description: "综合学习颜色、数字和字母的英语表达。",
      whyRecommend: "Cocomelon是全球最受欢迎的儿童频道之一，动画精美，歌曲洗脑，基础词汇全覆盖。",
      safetyNotes: "画面温馨，家庭场景为主，非常安全。",
      parentTips: "观看后可指着家中物品问孩子颜色的英文。"
    },
    {
      id: "english-003",
      category: "english",
      title: "Daily Routines | What Do You Do Every Day?",
      titleZh: "日常生活：你每天做什么？",
      youtubeId: "eUXkj6j6Ezw",
      channel: "Super Simple Songs",
      channelType: "official",
      duration: "3:30",
      durationMinutes: 3.5,
      thumbnail: "🌅",
      ageMin: 5,
      ageMax: 8,
      skills: ["日常词汇", "动词短语", "时间概念"],
      description: "学习起床、刷牙、吃饭等日常活动的英语表达。",
      whyRecommend: "贴近生活场景，实用性强，孩子容易理解和运用。",
      safetyNotes: "展示健康的日常生活习惯，正面引导。",
      parentTips: "可以在对应的日常场景中用英语和孩子对话。"
    },
    {
      id: "english-004",
      category: "english",
      title: "Weather Song for Kids | Sun, Rain, Wind, Snow",
      titleZh: "天气歌：晴天、雨天、风和雪",
      youtubeId: "rD6FRDd9Hew",
      channel: "Super Simple Songs",
      channelType: "official",
      duration: "2:45",
      durationMinutes: 2.75,
      thumbnail: "🌤️",
      ageMin: 4,
      ageMax: 7,
      skills: ["天气词汇", "自然现象", "形容词"],
      description: "学习各种天气的英语表达和相关动作。",
      whyRecommend: "配合动作学习，加深记忆，日常可以每天讨论天气练习。",
      safetyNotes: "内容轻松愉快，画风简洁可爱。",
      parentTips: "每天早上可以和孩子用英语讨论今天的天气。"
    },
    {
      id: "english-005",
      category: "english",
      title: "Feelings and Emotions Song | Happy, Sad, Angry",
      titleZh: "情绪词汇歌：开心、难过、生气",
      youtubeId: "UsISd1AMNYU",
      channel: "Super Simple Songs",
      channelType: "official",
      duration: "3:00",
      durationMinutes: 3,
      thumbnail: "😊",
      ageMin: 4,
      ageMax: 7,
      skills: ["情绪词汇", "表情认知", "情感表达"],
      description: "学习表达不同情绪的英语词汇，认识各种表情。",
      whyRecommend: "同时学习英语和情绪认知，一举两得，帮助孩子表达自己的感受。",
      safetyNotes: "正面展示情绪，教导健康的情绪表达。",
      parentTips: "当孩子有情绪时，可以问：How do you feel?"
    },

    // ==================== 科普探索 (5个) ====================
    {
      id: "science-001",
      category: "science",
      title: "All About Dinosaurs | National Geographic Kids",
      titleZh: "恐龙大百科",
      youtubeId: "BVLReTXdkPM",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "7:00",
      durationMinutes: 7,
      thumbnail: "🦕",
      ageMin: 5,
      ageMax: 9,
      skills: ["古生物知识", "科学思维", "词汇扩展"],
      description: "了解不同种类的恐龙，它们的特征和生活方式。",
      whyRecommend: "国家地理官方内容，信息准确权威，画面震撼但不恐怖，满足孩子对恐龙的好奇心。",
      safetyNotes: "画面经过处理，不含暴力捕食场景，适合儿童观看。",
      parentTips: "可以配合恐龙玩具或绘本进行拓展学习。"
    },
    {
      id: "science-002",
      category: "science",
      title: "The Solar System Song | Planet Song for Kids",
      titleZh: "太阳系之歌：认识八大行星",
      youtubeId: "mQrlgH97v94",
      channel: "KidsLearningTube",
      channelType: "educational",
      duration: "4:30",
      durationMinutes: 4.5,
      thumbnail: "🪐",
      ageMin: 5,
      ageMax: 9,
      skills: ["天文知识", "行星名称", "太阳系结构"],
      description: "用歌曲学习太阳系八大行星的名称和顺序。",
      whyRecommend: "太空主题对6岁孩子极具吸引力，歌曲帮助记忆行星顺序，科学启蒙的好起点。",
      safetyNotes: "纯科普内容，画面美观，适合儿童。",
      parentTips: "可以用水果做行星模型，帮助理解大小对比。"
    },
    {
      id: "science-003",
      category: "science",
      title: "How Does Your Heart Work? | Human Body for Kids",
      titleZh: "你的心脏是怎么工作的？",
      youtubeId: "9fRgFKiPl7Y",
      channel: "SciShow Kids",
      channelType: "official",
      duration: "5:30",
      durationMinutes: 5.5,
      thumbnail: "❤️",
      ageMin: 5,
      ageMax: 8,
      skills: ["人体知识", "器官功能", "科学思维"],
      description: "了解心脏的结构和功能，为什么心脏会跳动。",
      whyRecommend: "SciShow Kids专为儿童设计，讲解深入浅出，用动画清晰展示人体奥秘。",
      safetyNotes: "卡通化讲解，不含真实医学图像，适合儿童。",
      parentTips: "可以让孩子听自己和家人的心跳，感受心脏的工作。"
    },
    {
      id: "science-004",
      category: "science",
      title: "Why Do Leaves Change Color? | Fall Science",
      titleZh: "为什么树叶会变色？",
      youtubeId: "Y-DhVJVvrq0",
      channel: "SciShow Kids",
      channelType: "official",
      duration: "4:00",
      durationMinutes: 4,
      thumbnail: "🍂",
      ageMin: 5,
      ageMax: 8,
      skills: ["植物知识", "季节变化", "因果思维"],
      description: "探索秋天树叶变色的科学原理。",
      whyRecommend: "贴近自然生活，孩子容易观察验证，培养对身边自然现象的好奇心。",
      safetyNotes: "纯自然科普，内容温和积极。",
      parentTips: "秋天可以带孩子收集不同颜色的落叶，实地观察。"
    },
    {
      id: "science-005",
      category: "science",
      title: "Amazing Animals: Ocean Creatures",
      titleZh: "神奇动物：海洋生物",
      youtubeId: "HA2qCgV5Tqw",
      channel: "National Geographic Kids",
      channelType: "official",
      duration: "6:00",
      durationMinutes: 6,
      thumbnail: "🐙",
      ageMin: 4,
      ageMax: 8,
      skills: ["海洋知识", "动物认知", "生态意识"],
      description: "探索神奇的海洋世界，认识各种海洋生物。",
      whyRecommend: "国家地理官方出品，画面精美，展示真实海洋生物，激发孩子对自然的热爱。",
      safetyNotes: "画面唯美，不含捕食等刺激场景，对儿童友好。",
      parentTips: "可以结合海洋馆参观或海洋绘本拓展学习。"
    },

    // ==================== 情绪与品格 (5个) ====================
    {
      id: "emotion-001",
      category: "emotion",
      title: "Daniel Tiger: It's OK to Feel Sad Sometimes",
      titleZh: "丹尼尔老虎：难过也没关系",
      youtubeId: "mhDC1gMbD78",
      channel: "Daniel Tiger's Neighbourhood",
      channelType: "official",
      duration: "5:00",
      durationMinutes: 5,
      thumbnail: "🐯",
      ageMin: 4,
      ageMax: 7,
      skills: ["情绪认知", "情绪接纳", "自我安慰"],
      description: "学习接纳负面情绪，了解难过是正常的感受。",
      whyRecommend: "PBS Kids王牌节目，专门教导儿童社会情感技能，歌曲朗朗上口易记忆。",
      safetyNotes: "内容温暖治愈，正面引导情绪管理。",
      parentTips: "当孩子难过时，可以唱视频里的歌：It's OK to feel sad sometimes."
    },
    {
      id: "emotion-002",
      category: "emotion",
      title: "Sesame Street: Kindness | Being Kind to Others",
      titleZh: "芝麻街：善良与关爱",
      youtubeId: "kAo4-2UzgPo",
      channel: "Sesame Street",
      channelType: "official",
      duration: "4:30",
      durationMinutes: 4.5,
      thumbnail: "❤️",
      ageMin: 4,
      ageMax: 7,
      skills: ["善良品格", "同理心", "助人行为"],
      description: "学习如何对他人展现善意和关爱。",
      whyRecommend: "芝麻街50多年品牌，品格教育权威，通过可爱角色传递善良的重要性。",
      safetyNotes: "内容纯净正面，传递积极价值观。",
      parentTips: "鼓励孩子每天做一件善良的小事，晚上分享。"
    },
    {
      id: "emotion-003",
      category: "emotion",
      title: "How to Be a Good Friend | Social Skills for Kids",
      titleZh: "如何做一个好朋友",
      youtubeId: "Sg9JYJlPv1w",
      channel: "Learning Songs",
      channelType: "educational",
      duration: "3:30",
      durationMinutes: 3.5,
      thumbnail: "🤝",
      ageMin: 5,
      ageMax: 8,
      skills: ["社交技能", "友谊", "分享合作"],
      description: "学习交朋友的技巧：分享、倾听、合作。",
      whyRecommend: "幼小衔接关键技能，帮助孩子在学校建立良好的人际关系。",
      safetyNotes: "正面社交引导，内容健康向上。",
      parentTips: "可以角色扮演，练习视频中提到的交友技巧。"
    },
    {
      id: "emotion-004",
      category: "emotion",
      title: "Taking Turns | Cooperation Song for Kids",
      titleZh: "轮流玩：合作歌",
      youtubeId: "NvmziBpjAIU",
      channel: "Super Simple Songs",
      channelType: "official",
      duration: "2:30",
      durationMinutes: 2.5,
      thumbnail: "🔄",
      ageMin: 4,
      ageMax: 7,
      skills: ["轮流等待", "耐心", "公平意识"],
      description: "学习轮流等待的重要性和方法。",
      whyRecommend: "轮流是重要的社交规则，歌曲简单好学，帮助孩子理解并实践。",
      safetyNotes: "内容积极正面，场景贴近儿童生活。",
      parentTips: "玩游戏时引用歌词：Taking turns is fun!"
    },
    {
      id: "emotion-005",
      category: "emotion",
      title: "I Can Do Hard Things | Growth Mindset for Kids",
      titleZh: "我能做到困难的事：成长型心态",
      youtubeId: "iE7R6KUFGak",
      channel: "GoNoodle",
      channelType: "official",
      duration: "4:00",
      durationMinutes: 4,
      thumbnail: "💪",
      ageMin: 5,
      ageMax: 9,
      skills: ["成长心态", "自信心", "坚持不懈"],
      description: "培养面对困难的勇气和'我能行'的心态。",
      whyRecommend: "成长型心态是学业成功的关键，帮助孩子建立面对挑战的积极态度。",
      safetyNotes: "内容励志正面，配合动作充满活力。",
      parentTips: "孩子遇到困难时，一起唱：I can do hard things!"
    },

    // ==================== 专注力与脑力 (5个) ====================
    {
      id: "brain-001",
      category: "brain",
      title: "Spot the Difference | Visual Puzzle for Kids",
      titleZh: "找不同：视觉挑战",
      youtubeId: "8ld9F-2yVlM",
      channel: "Muffalo Potato",
      channelType: "educational",
      duration: "5:00",
      durationMinutes: 5,
      thumbnail: "👀",
      ageMin: 5,
      ageMax: 9,
      skills: ["观察力", "注意细节", "专注力"],
      description: "在两幅相似图片中找出不同之处。",
      whyRecommend: "经典的专注力训练，画面有趣，难度适中，孩子很有成就感。",
      safetyNotes: "纯益智内容，无任何不适元素。",
      parentTips: "可以暂停视频让孩子自己找，再播放答案验证。"
    },
    {
      id: "brain-002",
      category: "brain",
      title: "Memory Game for Kids | What's Missing?",
      titleZh: "记忆游戏：少了什么？",
      youtubeId: "dH9cxzHDqYM",
      channel: "Smile and Learn",
      channelType: "educational",
      duration: "6:00",
      durationMinutes: 6,
      thumbnail: "🧩",
      ageMin: 4,
      ageMax: 7,
      skills: ["短期记忆", "观察力", "专注力"],
      description: "观察物品，然后回忆哪个物品消失了。",
      whyRecommend: "记忆力训练对学习至关重要，游戏形式有趣，逐步增加难度。",
      safetyNotes: "卡通风格，内容纯净，适合独立观看。",
      parentTips: "可以在家用玩具模仿游戏，加强训练效果。"
    },
    {
      id: "brain-003",
      category: "brain",
      title: "Which One is Different? | Odd One Out Puzzles",
      titleZh: "哪个不一样？找不同类",
      youtubeId: "pLtJxqFQaU4",
      channel: "Smile and Learn",
      channelType: "educational",
      duration: "5:30",
      durationMinutes: 5.5,
      thumbnail: "❓",
      ageMin: 5,
      ageMax: 8,
      skills: ["分类思维", "逻辑推理", "观察比较"],
      description: "找出一组物品中与众不同的那一个。",
      whyRecommend: "分类是重要的逻辑思维基础，帮助孩子学会归纳和比较。",
      safetyNotes: "纯益智内容，画面友好。",
      parentTips: "日常可以玩类似游戏：桌上放几样东西，问哪个不一样。"
    },
    {
      id: "brain-004",
      category: "brain",
      title: "Follow the Pattern | Logic Puzzles for Kids",
      titleZh: "规律推理：下一个是什么？",
      youtubeId: "cHJJPQu0QtA",
      channel: "Kids Academy",
      channelType: "educational",
      duration: "4:30",
      durationMinutes: 4.5,
      thumbnail: "🔮",
      ageMin: 5,
      ageMax: 8,
      skills: ["规律推理", "逻辑思维", "预测能力"],
      description: "观察规律，预测接下来会出现什么。",
      whyRecommend: "规律推理是数学和逻辑的基础，视频由浅入深，适合6岁孩子。",
      safetyNotes: "教育内容，画面清晰简洁。",
      parentTips: "可以用积木或彩色珠子创造规律让孩子接续。"
    },
    {
      id: "brain-005",
      category: "brain",
      title: "Maze Puzzles for Kids | Find the Way",
      titleZh: "迷宫挑战：找出路",
      youtubeId: "s1l25MUvGR4",
      channel: "Smile and Learn",
      channelType: "educational",
      duration: "5:00",
      durationMinutes: 5,
      thumbnail: "🌀",
      ageMin: 5,
      ageMax: 8,
      skills: ["空间思维", "路径规划", "问题解决"],
      description: "帮助角色找到走出迷宫的路径。",
      whyRecommend: "迷宫是经典的空间思维训练，培养规划和预判能力。",
      safetyNotes: "卡通迷宫，场景友好无压力。",
      parentTips: "可以配合纸质迷宫书，让孩子用手指或铅笔走迷宫。"
    },

    // ==================== 音乐与运动 (5个) ====================
    {
      id: "music-001",
      category: "music",
      title: "Head Shoulders Knees and Toes | Action Song",
      titleZh: "头肩膝脚趾：身体律动",
      youtubeId: "h4eueDYPTIg",
      channel: "Super Simple Songs",
      channelType: "official",
      duration: "2:30",
      durationMinutes: 2.5,
      thumbnail: "🙆",
      ageMin: 3,
      ageMax: 7,
      skills: ["身体部位", "协调性", "听指令"],
      description: "经典的身体部位歌曲，边唱边做动作。",
      whyRecommend: "经典儿歌，全球流行，帮助孩子认识身体部位同时活动身体。",
      safetyNotes: "动作简单安全，节奏适中。",
      parentTips: "可以逐渐加快速度，增加挑战和乐趣。"
    },
    {
      id: "music-002",
      category: "music",
      title: "Freeze Dance | Movement Song for Kids",
      titleZh: "定格舞：听音乐动起来",
      youtubeId: "2UcZWXvgMZE",
      channel: "The Kiboomers",
      channelType: "official",
      duration: "3:30",
      durationMinutes: 3.5,
      thumbnail: "🕺",
      ageMin: 4,
      ageMax: 8,
      skills: ["听觉反应", "自控力", "大肌肉运动"],
      description: "音乐响起时跳舞，音乐停止时定格。",
      whyRecommend: "训练听觉反应和自控力，同时让孩子充分活动，释放能量。",
      safetyNotes: "室内可安全进行，不需要额外器材。",
      parentTips: "全家一起玩，增加亲子互动乐趣。"
    },
    {
      id: "music-003",
      category: "music",
      title: "Animal Dance | Move Like Animals Song",
      titleZh: "动物舞：模仿动物动起来",
      youtubeId: "HpOe8lngp_o",
      channel: "GoNoodle",
      channelType: "official",
      duration: "4:00",
      durationMinutes: 4,
      thumbnail: "🐸",
      ageMin: 4,
      ageMax: 8,
      skills: ["模仿能力", "大肌肉运动", "想象力"],
      description: "模仿不同动物的动作和声音。",
      whyRecommend: "GoNoodle专为儿童设计运动内容，动作有趣，孩子很喜欢。",
      safetyNotes: "动作设计安全，适合室内进行。",
      parentTips: "可以问孩子想模仿什么动物，鼓励创意。"
    },
    {
      id: "music-004",
      category: "music",
      title: "If You're Happy and You Know It | Classic Kids Song",
      titleZh: "如果感到幸福你就拍拍手",
      youtubeId: "l4WNrvVjiTw",
      channel: "Super Simple Songs",
      channelType: "official",
      duration: "2:45",
      durationMinutes: 2.75,
      thumbnail: "👏",
      ageMin: 3,
      ageMax: 7,
      skills: ["情绪表达", "节奏感", "听指令"],
      description: "经典互动儿歌，通过动作表达快乐。",
      whyRecommend: "全球经典儿歌，简单好学，帮助孩子用身体表达积极情绪。",
      safetyNotes: "动作简单安全，适合任何场合。",
      parentTips: "可以创造新歌词：如果想睡觉你就打哈欠..."
    },
    {
      id: "music-005",
      category: "music",
      title: "Yoga for Kids | Cosmic Kids Yoga Adventure",
      titleZh: "儿童瑜伽：太空冒险",
      youtubeId: "LhYtcadR9nw",
      channel: "Cosmic Kids Yoga",
      channelType: "official",
      duration: "12:00",
      durationMinutes: 12,
      thumbnail: "🧘",
      ageMin: 4,
      ageMax: 9,
      skills: ["平衡协调", "专注力", "身心放松"],
      description: "跟随故事做瑜伽动作，放松身心。",
      whyRecommend: "Cosmic Kids是儿童瑜伽领导品牌，将瑜伽融入故事，孩子很容易跟着做。",
      safetyNotes: "动作设计考虑儿童安全，不含高难度姿势。",
      parentTips: "睡前做有助于帮助孩子平静下来，改善睡眠。"
    }
  ]
};

// 导出供其他模块使用
if (typeof module !== 'undefined' && module.exports) {
  module.exports = videoDatabase;
}
